spring: 
   profiles: 
      active: 
        - dev

---
spring: 
   profiles: dev
   application: 
      name: microservice-config-learn-dev
      
---
spring: 
   profiles: test
   application: 
      name: microservice-config-learn-test